apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - image: mysql:8.3
          name: mysql
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "false"

            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

            - name: MYSQL_DATABASE
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

          ports:
            - containerPort: 3306
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim